version: '3'
services:
  factorio_server:
    image: derenderkeks/factorio-server
    ports:
      - '34197/udp:34197/udp'
    ## RCON settings ##
    #  - '27015:27015'
    #environment:
    #  - RCONPORT=27015
    #  - RCONPASSWORD=
    volumes:
      - './config:/srv/factorio/config'
      - './saves:/srv/factorio/saves'
      - './mods:/srv/factorio/mods'
    restart: always
